name: CI

on:
  - push
  - pull_request

env:
  NEXT_PUBLIC_NOTION_DATABASE_URL: ${{ secrets.NEXT_PUBLIC_NOTION_DATABASE_URL }}
  NOTION_API_TOKEN: ${{ secrets.NOTION_API_TOKEN }}
  USE_TOKEN_AUTH: ${{ secrets.USE_TOKEN_AUTH }}

jobs:
  jest:
    name: Jest on Node.js ${{ matrix.node-version }}
    runs-on: macos-latest
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        node-version:
          - 16
          - 14
          - 12
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - run: yarn jest

  chrome:
    name: E2E on chrome
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v2
        with:
          browser: chrome

  firefox:
    name: E2E on firefox
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v2
        with:
          browser: firefox
